### PR TITLE
Upgrading to 0.7.2

### PR DESCRIPTION
**Pull request by jackschd**

### CODE REVIEW

**Comment by jackschd** [comment]
<p>Agreed</p>

---

 <a href='https://app.reviewnb.com/atoti/notebooks/pull/390/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jackschd** [comment]
<p>Fair point. I'll move that line down to where it's going to be used.</p>

---

 <a href='https://app.reviewnb.com/atoti/notebooks/pull/390/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jackschd** [comment]
<p>I was trying to keep the datastore stuff all together, and I do say this...</p><p>"We'll see how we can use this new type of hierarchy a little later when we discuss lookup measures"</p>

---

 <a href='https://app.reviewnb.com/atoti/notebooks/pull/390/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jackschd** [comment]
<p>That's new to me - I'll add a note to highlight an alternative way of achieving the same thing.</p>

---

 <a href='https://app.reviewnb.com/atoti/notebooks/pull/390/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jackschd** [comment]
<p>I'll double-check...</p>

---

 <a href='https://app.reviewnb.com/atoti/notebooks/pull/390/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jackschd** [comment]
<p>You're correct. I'll change this.</p>

---

 <a href='https://app.reviewnb.com/atoti/notebooks/pull/390/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jackschd** [comment]
<p>Definitely the lookup one.</p>

---

 <a href='https://app.reviewnb.com/atoti/notebooks/pull/390/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jackschd** [comment]
<p>Nice</p>

---

 <a href='https://app.reviewnb.com/atoti/notebooks/pull/390/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jackschd** [comment]
<p>Agreed.</p>

---

 <a href='https://app.reviewnb.com/atoti/notebooks/pull/390/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jackschd** [comment]
<p>Added.</p>

---

 <a href='https://app.reviewnb.com/atoti/notebooks/pull/390/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by HuifangYeo** [comment]
<p>Just a suggestion - the placement of the Lookup tables section is a bit disjoint in the flow. I think it might flow better if you put it just after the "Joining tables in database" section and before the "Visualizing the cube". Because effectively, you haven't done any lookup here. You are merely joining the tables. So it should actually be grouped with the Loading data, and probably with a subheader. </p>

---

 <a href='https://app.reviewnb.com/atoti/notebooks/pull/390/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by HuifangYeo** [comment]
<p>It would be great if you could replace all the usage of <code>cube.levels</code> with <code>levels</code> instead, since you have created the variable for it.  </p>

---

 <a href='https://app.reviewnb.com/atoti/notebooks/pull/390/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jackschd** [comment]
<p>Agreed</p>

---

 <a href='https://app.reviewnb.com/atoti/notebooks/pull/390/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jackschd** [comment]
<p>Yep</p>

---

 <a href='https://app.reviewnb.com/atoti/notebooks/pull/390/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jackschd** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/atoti/notebooks/pull/390/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jackschd** [comment]
<p>Corrected</p>

---

 <a href='https://app.reviewnb.com/atoti/notebooks/pull/390/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jackschd** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/atoti/notebooks/pull/390/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jackschd** [comment]
<p>Removed as unused</p>

---

 <a href='https://app.reviewnb.com/atoti/notebooks/pull/390/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jackschd** [comment]
<p>Re-worked as discussed</p>

---

 <a href='https://app.reviewnb.com/atoti/notebooks/pull/390/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jackschd** [comment]
<p>Re-worked as discussed</p>

---

 <a href='https://app.reviewnb.com/atoti/notebooks/pull/390/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jackschd** [comment]
<p>Corrected</p>

---

 <a href='https://app.reviewnb.com/atoti/notebooks/pull/390/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by HuifangYeo — APPROVED** [review]

**Pull request merged**
