### PR TITLE
Update SACCR to 0.6.0

### PR DESCRIPTION
**Pull request by bloussou**

### CODE REVIEW

**Comment by HuifangYeo** [comment]
Hi @bloussou,

Do you mind explaining why we need `detached_process` for this notebook and what it does?
I've encountered the below exception in Windows:

<details><pre>
detached_process: expecting a running server with Py4J listening on port 25333
---------------------------------------------------------------------------
ConnectionRefusedError                    Traceback (most recent call last)
<ipython-input-2-98c9f763ce55> in <module>
      1 import atoti as tt
      2 
----> 3 session = tt.create_session(config={"user_content_storage": "./content"}, detached_process=True) #
      4 session.link()

C:\Apps\miniconda3\envs\rc\lib\site-packages\atoti\_type_utils.py in typechecked_func_wrapper(*args, **kwargs)
    188 
    189             # Call the actual function.
--> 190             return self._func(*args, **kwargs)
    191 
    192         # Mark the function as typechecked and return it.

C:\Apps\miniconda3\envs\rc\lib\site-packages\atoti\_sessions.py in create_session(self, name, config, **kwargs)
     50         """
     51         self._clear_duplicate_sessions(name)
---> 52         session = Session(
     53             name,
     54             config=SessionConfig._from_mapping(config or {}),

C:\Apps\miniconda3\envs\rc\lib\site-packages\atoti\_type_utils.py in typechecked_func_wrapper(*args, **kwargs)
    188 
    189             # Call the actual function.
--> 190             return self._func(*args, **kwargs)
    191 
    192         # Mark the function as typechecked and return it.

C:\Apps\miniconda3\envs\rc\lib\site-packages\atoti\session.py in __init__(self, name, config, detached_process)
     55     ):
     56         """Create the session and the Java gateway."""
---> 57         super().__init__(
     58             name, config=config, detached_process=detached_process, distributed=False
     59         )

C:\Apps\miniconda3\envs\rc\lib\site-packages\atoti\_local_session.py in __init__(self, name, config, detached_process, distributed)
     48         self._config = config
     49 
---> 50         self._create_subprocess_and_java_api(
     51             detached_process=detached_process, distributed=distributed
     52         )

C:\Apps\miniconda3\envs\rc\lib\site-packages\atoti\_local_session.py in _create_subprocess_and_java_api(self, detached_process, distributed)
     83             py4j_java_port = self._server_subprocess.py4j_java_port
     84 
---> 85         self._java_api: JavaApi = JavaApi(
     86             py4j_java_port=py4j_java_port, distributed=distributed
     87         )

C:\Apps\miniconda3\envs\rc\lib\site-packages\atoti\exceptions.py in catch_py4j_exceptions(java_api, *args, **kwargs)
     64     def catch_py4j_exceptions(java_api: JavaApi, *args: Any, **kwargs: Any) -> Any:
     65         try:
---> 66             return method(java_api, *args, **kwargs)
     67         except Py4JJavaError as java_exception:
     68             cause = (

C:\Apps\miniconda3\envs\rc\lib\site-packages\atoti\_java_api.py in __init__(self, py4j_java_port, distributed)
    108     ):
    109         """Create the Java gateway."""
--> 110         self.gateway = JavaApi._create_py4j_gateway(py4j_java_port)
    111         self.java_session: Any = self.gateway.entry_point
    112         self.java_session.api(distributed)

C:\Apps\miniconda3\envs\rc\lib\site-packages\atoti\_java_api.py in _create_py4j_gateway(java_port)
    137         # ignore type next line because we do some Java calls
    138         gateway_server.resetCallbackClient(
--> 139             gateway_server.getCallbackClient().getAddress(), python_port  # type: ignore
    140         )
    141 

C:\Apps\miniconda3\envs\rc\lib\site-packages\atoti\_vendor\atotipy4j\java_gateway.py in __call__(self, *args)
   1310             proto.END_COMMAND_PART
   1311 
-> 1312         answer = self.gateway_client.send_command(command)
   1313         return_value = get_return_value(
   1314             answer, self.gateway_client, self.target_id, self.name)

C:\Apps\miniconda3\envs\rc\lib\site-packages\atoti\_vendor\atotipy4j\java_gateway.py in send_command(self, command, retry, binary)
   1038          if `binary` is `True`.
   1039         """
-> 1040         connection = self._get_connection()
   1041         try:
   1042             response = connection.send_command(command)

C:\Apps\miniconda3\envs\rc\lib\site-packages\atoti\_vendor\atotipy4j\clientserver.py in _get_connection(self)
    296 
    297         if connection is None or connection.socket is None:
--> 298             connection = self._create_new_connection()
    299         return connection
    300 

C:\Apps\miniconda3\envs\rc\lib\site-packages\atoti\_vendor\atotipy4j\clientserver.py in _create_new_connection(self)
    303             self.java_parameters, self.python_parameters,
    304             self.gateway_property, self)
--> 305         connection.connect_to_java_server()
    306         self.set_thread_connection(connection)
    307         return connection

C:\Apps\miniconda3\envs\rc\lib\site-packages\atoti\_vendor\atotipy4j\clientserver.py in connect_to_java_server(self)
    417                 self.socket = self.ssl_context.wrap_socket(
    418                     self.socket, server_hostname=self.java_address)
--> 419             self.socket.connect((self.java_address, self.java_port))
    420             self.stream = self.socket.makefile("rb")
    421             self.is_connected = True

ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
</pre></details>

**Comment by bloussou** [comment]
It's ready for review, I have fixed issues, I'm not sure about the new sentences to describe simulations, I let you this part since I'm not really used to this use case

**Comment by HuifangYeo** [comment]
@bloussou,

I'm not sure about the below:

```
recalibration = cube.create_parameter_simulation(
    "Option Volatility What-If",
    measure_name="Supervisory_Option_Volatility_Simulation",
    default_value=1,
    levels=[l["AssetClass"], l["SubClass"]],
)
```

What if the original value in the table for `SupervisoryOptionVolatility.VALUE` is `x` and I want to replace it with the value `1`?
In this case, the below snippet would cause it to take the value of `x` over `1`. 
```
m["Supervisory_Option_Volatility"] = tt.agg.sum(
    tt.where(
        m["Supervisory_Option_Volatility_Simulation"] == 1,
        m["SupervisoryOptionVolatility.VALUE"],
        m["Supervisory_Option_Volatility_Simulation"],
    ),
    scope=tt.scope.origin(l["AssetClass"], l["SubClass"]),
)
```

**Comment by APolyakova** [comment]
Hi Hui Fang, the upgrade looks great, and also the numbers match! meaning everything is as correct as before.
Regarding the simulations, I suggest to keep the section Supervisory delta adjustments - [52.38] - [52.41] as is, and in that section define the measure as follows:
m["Supervisory_Option_Volatility"] = tt.value(
    supervisoryParameters_table["SupervisoryOptionVolatility"], levels=[l["TradeId"]]
)
 
Then keep using it. 
Later in the Simulations sections let's redefine that measure complete. So basically let's put the rows starting with "recalibration =" and ending with "cube.query(
    m["SupervisoryOptionVolatility.VALUE"]," into the simulations section. This way the story flow is as before.

Thank you
Anastasia

**Comment by HuifangYeo** [comment]
Hi @APolyakova / @bloussou, I have updated the parameter simulation.
Please have a look.

@APolyakova, I cannot find the dashboard shown by the GIF nor the Risk Factor level. Could you advise how we could build that dashboard or should we remove the GIF?

**Comment by bloussou** [comment]
Ok for me :+1:

**Comment by APolyakova** [comment]
Hi team, I updated the gif. I'm happy with the PR

**Review by APolyakova — APPROVED** [review]

**Pull request merged**
