### PR TITLE
Food proccessing

### PR DESCRIPTION
**Pull request by rvs36**
The final version of the food processing notebook

### CODE REVIEW

**Review by HuifangYeo — COMMENTED** [review]
Hi @rvs36,

Can you:
- update ./README.md to add this notebook under Retail
- remove the csv files (uploaded to s3)

**Comment by HuifangYeo** [comment]
This notebook focuses on ~making~ resolving the issue of inventory management... .... the inventory acquisition and ~hence~ _consequently_ the manufacturing capabilities. <= too many hence in the sentence and it's very long. Maybe you can break it into shorter sentences.

_When it comes to sales for manufacturing industries_, both the extreme scenarios are unfavorable <= restructured the sentence 

Maybe you can provide links to the definition of dead inventory and stock out.

**Comment by rvs36** [comment]
I have made the suggested changes, requesting you to please approve.

**Review by HuifangYeo — APPROVED** [review]
Hi @rvs36,

Please see the [reviews](https://app.reviewnb.com/atoti/notebooks/blob/agro/retail%2Ffood-processing%2Fmain.ipynb/file).

I'm approving the notebook in advance since mainly are linguistic changes.

**Pull request merged**
