### PR TITLE
Influencers analysis

### PR DESCRIPTION
**Pull request by arielibaba**

### CODE REVIEW

**Comment by bloussou** [comment]
CI pass :rocket:

**Review by bloussou — CHANGES_REQUESTED** [review]
Can you use [f-string](https://realpython.com/python-f-strings/) instead of `.format()` ?

**Comment by bloussou** [comment]
New comments comments on review nb to fix

**Review by bloussou — APPROVED** [review]
Nice :+1:

**Review by HuifangYeo — COMMENTED** [review]
Is it possible to load data files onto S3?

**Comment by HuifangYeo** [comment]
Kindly edit PR to merge into https://github.com/atoti/notebooks/tree/0.6.0 instead.

**Comment by bloussou** [comment]
> Kindly edit PR to merge into https://github.com/atoti/notebooks/tree/0.6.0 instead.

This is written in 0.5.5 so if it is supposed to be out this week it has to be merged in `master`

**Review by rvs36 — APPROVED** [review]

**Pull request merged**
